### ISSUE TITLE
您好，能详细解析一下drawLine, drawPoint, drawPolygon这三个函数吗？

### ISSUE THREAD

**Issue by yhdjyyzk** [bingqixuan/MVT-Process#1]
https://github.com/bingqixuan/MVT-Process/blob/e5540b060cc09029c12b853e93f34f16a4b7896c/src/viz.js#L95

谢谢。

**Comment by bingqixuan** [comment]
我是根据mapbox的矢量瓦片的图形编码规则来写的。这有他的中文规范：https://github.com/jingsam/vector-tile-spec/blob/master/2.1/README_zh.md

**Comment by bingqixuan** [comment]
> [MVT-Process/src/viz.js](https://github.com/bingqixuan/MVT-Process/blob/e5540b060cc09029c12b853e93f34f16a4b7896c/src/viz.js#L95)
> 
> Line 95 in [e5540b0](/bingqixuan/MVT-Process/commit/e5540b060cc09029c12b853e93f34f16a4b7896c)
> 
>  drawPoint(context, feature, layer); 
> 谢谢。

我是根据mapbox的矢量瓦片的图形编码规则来写的。这有他的中文规范：https://github.com/jingsam/vector-tile-spec/blob/master/2.1/README_zh.md

**Comment by yhdjyyzk** [comment]
> > [MVT-Process/src/viz.js](https://github.com/bingqixuan/MVT-Process/blob/e5540b060cc09029c12b853e93f34f16a4b7896c/src/viz.js#L95)
> > Line 95 in [e5540b0](/bingqixuan/MVT-Process/commit/e5540b060cc09029c12b853e93f34f16a4b7896c)
> > drawPoint(context, feature, layer);
> > 谢谢。
> 
> 我是根据mapbox的矢量瓦片的图形编码规则来写的。这有他的中文规范：https://github.com/jingsam/vector-tile-spec/blob/master/2.1/README_zh.md

谢谢。
